### ISSUE TITLE
[f.suggest] Вернуть импортирование изображения

### ISSUE THREAD

**Issue by vlfz** [Flame-Developers/Flame#10]
Как я понял - у старой версии бота команда suggest также импортировала изображение пользователя
![image](https://user-images.githubusercontent.com/32297717/127535482-59ad6c6f-5d41-416a-9d84-786899325620.png)

Сейчас же такого нет.
![image](https://user-images.githubusercontent.com/32297717/127535513-4cb37db5-63fb-4a69-9394-563107ee1ff1.png)

Я бы и сам добавил, но боюсь что мой код кому-то не понравится. /shrug

**Comment by TheFerryn** [comment]
Введено в 5.2.3.
