### ISSUE TITLE
Отсутствие слеш команды в боте.

### ISSUE THREAD

**Issue by MrLivixx** [Flame-Developers/Flame#11]
Судя по всему, если есть файл "StopCommand" то значит есть слеш команда стоп музыки, но её нет....
![image](https://user-images.githubusercontent.com/54632865/127567113-01e6db43-bb2e-4685-a7c8-c4eef2ef60e2.png)

**Comment by TheFerryn** [comment]
![image](https://user-images.githubusercontent.com/67315369/128751464-b2f57b4d-5014-45ec-a4cb-1fc37fa613e0.png)
