### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by FedorLap2006** [Flame-Developers/Flame#5]
Предлагаю добавить поддержку CI/CD (на GH Actions).

**Comment by arslee07** [comment]
гений

**Comment by Enslavedd** [comment]
> гений

так то ты тоже гений, в PR об этом писать

**Comment by arslee07** [comment]
ikr- 😎

**Comment by arslee07** [comment]
он

**Comment by arslee07** [comment]
именно он

**Comment by vlfz** [comment]
> Предлагаю добавить поддержку CI/CD (на GH Actions).

не

**Comment by FedorLap2006** [comment]
> > Предлагаю добавить поддержку CI/CD (на GH Actions).
> 
> не

поздно

**Comment by vlfz** [comment]
> > > Предлагаю добавить поддержку CI/CD (на GH Actions).
> > 
> > 
> > не
> 
> поздно, ферун уже этим занялся

не

**Comment by arslee07** [comment]
тест (я это отправил по почте кек)

чт, 24 июн. 2021 г., 19:17 cipherka ***@***.***>:

**Comment by arslee07** [comment]
мда с почтой тут явно беда
